use std::env;

use anyhow::{Context, Result};
use flux::{AggregateRepository, AggregateRoot, GraphSaveMode, Include, RelationMetadata};
use flux_derive::{AggregateRoot, Entity, MongoEntity};
use flux_mongodb::{MongoAggregate, MongoObjectId, MongoRepository};
use mongodb::{
    bson::{doc, oid::ObjectId},
    Client,
};

#[derive(Clone, Debug, Entity, MongoEntity)]
#[collection_name = "cookbook_mongo_profiles"]
struct UserProfile {
    #[primary_key]
    id: MongoObjectId,
    user_id: MongoObjectId,
    bio: String,
}

#[derive(Clone, Debug, Entity, MongoEntity, AggregateRoot)]
#[collection_name = "cookbook_mongo_users_has_one"]
struct User {
    #[primary_key]
    id: MongoObjectId,
    name: String,

    #[has_one(
        foreign_key = "user_id",
        references = "id",
        on_replace = "delete_missing"
    )]
    profile: Option<UserProfile>,
}

#[flux_mongodb::async_trait]
impl MongoAggregate for User {
    async fn load_relations(
        repository: &MongoRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "profile") {
            aggregate.profile = repository
                .load_has_one::<UserProfile, _>(relation("profile"), &aggregate.id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_one::<UserProfile, _>(
                relation("profile"),
                aggregate.profile.as_ref(),
                &aggregate.id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_one::<UserProfile, _>(
                relation("profile"),
                aggregate.profile.as_ref(),
                &aggregate.id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &MongoRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<UserProfile, _>(relation("profile"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let database = connect_mongo().await?;
    clear_collections(
        &database,
        &["cookbook_mongo_users_has_one", "cookbook_mongo_profiles"],
    )
    .await?;

    let repo = MongoRepository::<User>::new(database);
    let user_id = MongoObjectId(ObjectId::new());
    let user = User {
        id: user_id,
        name: "Ada".to_string(),
        profile: Some(UserProfile {
            id: MongoObjectId(ObjectId::new()),
            user_id,
            bio: "First programmer".to_string(),
        }),
    };

    let saved = repo
        .save_graph(&user, GraphSaveMode::UpsertChildren)
        .await
        .context("save Mongo has-one graph")?;
    let loaded = repo
        .find_graph_by_id(&saved.id, &[User::profile()])
        .await
        .context("load Mongo has-one graph")?;

    assert!(loaded.profile.is_some());

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    User::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn clear_collections(database: &mongodb::Database, names: &[&str]) -> Result<()> {
    for name in names {
        database
            .collection::<mongodb::bson::Document>(name)
            .delete_many(doc! {})
            .await
            .with_context(|| format!("clear Mongo collection {name}"))?;
    }
    Ok(())
}

async fn connect_mongo() -> Result<mongodb::Database> {
    let uri = env::var("MONGO_URI").unwrap_or_else(|_| "mongodb://localhost:27017".to_string());
    let database_name = env::var("MONGO_DATABASE").unwrap_or_else(|_| "flux_cookbook".to_string());
    let client = Client::with_uri_str(&uri)
        .await
        .context("failed to connect to MongoDB")?;
    client
        .database("admin")
        .run_command(doc! { "ping": 1 })
        .await
        .context("failed to ping MongoDB")?;
    Ok(client.database(&database_name))
}
