use std::env;

use anyhow::{Context, Result};
use flux::{AggregateRepository, AggregateRoot, GraphSaveMode, Include, RelationMetadata};
use flux_derive::{AggregateRoot, Entity, MongoEntity};
use flux_mongodb::{MongoAggregate, MongoObjectId, MongoRepository};
use mongodb::{
    bson::{doc, oid::ObjectId},
    Client,
};

#[derive(Clone, Debug, Entity, MongoEntity)]
#[collection_name = "cookbook_mongo_courses"]
struct Course {
    #[primary_key]
    id: MongoObjectId,
    title: String,
}

#[derive(Clone, Debug, Entity, MongoEntity, AggregateRoot)]
#[collection_name = "cookbook_mongo_students"]
struct Student {
    #[primary_key]
    id: MongoObjectId,
    name: String,

    #[many_to_many(
        join_table = "cookbook_mongo_enrollments",
        source_key = "student_id",
        target_key = "course_id",
        target_primary_key = "_id",
        on_replace = "delete_missing"
    )]
    courses: Vec<Course>,
}

#[flux_mongodb::async_trait]
impl MongoAggregate for Student {
    async fn load_relations(
        repository: &MongoRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "courses") {
            aggregate.courses = repository
                .load_many_to_many::<Course, _>(relation("courses"), &aggregate.id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_many_to_many::<Course, _>(
                relation("courses"),
                aggregate.courses.as_slice(),
                &aggregate.id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_many_to_many::<Course, _>(
                relation("courses"),
                aggregate.courses.as_slice(),
                &aggregate.id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &MongoRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_many_to_many_links(relation("courses"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let database = connect_mongo().await?;
    clear_collections(
        &database,
        &[
            "cookbook_mongo_students",
            "cookbook_mongo_courses",
            "cookbook_mongo_enrollments",
        ],
    )
    .await?;

    let repo = MongoRepository::<Student>::new(database);
    let rust_course = Course {
        id: MongoObjectId(ObjectId::new()),
        title: "Rust".to_string(),
    };
    let databases_course = Course {
        id: MongoObjectId(ObjectId::new()),
        title: "Databases".to_string(),
    };
    let student = Student {
        id: MongoObjectId(ObjectId::new()),
        name: "Ada".to_string(),
        courses: vec![rust_course.clone(), databases_course],
    };

    repo.save_graph(&student, GraphSaveMode::ReplaceChildren)
        .await
        .context("save Mongo many-to-many graph")?;
    let replacement = Student {
        courses: vec![rust_course],
        ..student
    };
    let saved = repo
        .save_graph(&replacement, GraphSaveMode::ReplaceChildren)
        .await
        .context("replace Mongo many-to-many links")?;

    assert_eq!(saved.courses.len(), 1);

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    Student::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn clear_collections(database: &mongodb::Database, names: &[&str]) -> Result<()> {
    for name in names {
        database
            .collection::<mongodb::bson::Document>(name)
            .delete_many(doc! {})
            .await
            .with_context(|| format!("clear Mongo collection {name}"))?;
    }
    Ok(())
}

async fn connect_mongo() -> Result<mongodb::Database> {
    let uri = env::var("MONGO_URI").unwrap_or_else(|_| "mongodb://localhost:27017".to_string());
    let database_name = env::var("MONGO_DATABASE").unwrap_or_else(|_| "flux_cookbook".to_string());
    let client = Client::with_uri_str(&uri)
        .await
        .context("failed to connect to MongoDB")?;
    client
        .database("admin")
        .run_command(doc! { "ping": 1 })
        .await
        .context("failed to ping MongoDB")?;
    Ok(client.database(&database_name))
}
