[workspace]
members = [
    "examples/mongodb-bulk",
    "examples/mongodb-crud-filter",
    "examples/mongodb-graph-delete",
    "examples/mongodb-graph-save",
    "examples/mongodb-has-many",
    "examples/mongodb-has-one",
    "examples/mongodb-many-to-many",
    "examples/mongodb-pagination-filter",
    "examples/mongodb-to-postgres",
    "examples/mongodb-transaction-rollback",
    "examples/postgres-bulk",
    "examples/postgres-crud",
    "examples/postgres-generated-id",
    "examples/postgres-graph-delete",
    "examples/postgres-graph-save",
    "examples/postgres-has-many",
    "examples/postgres-has-one",
    "examples/postgres-many-to-many",
    "examples/postgres-pagination-filter",
    "examples/postgres-transaction-rollback",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["leonardo merelles <leonardo.merelles@zetti.tech>"]
homepage = "https://github.com/merelles/flux"
license = "MIT"
repository = "https://github.com/merelles/flux"

[workspace.dependencies]
anyhow = "1"
dotenvy = "0.15"
flux = { git = "https://github.com/merelles/flux", package = "flux" }
flux-derive = { git = "https://github.com/merelles/flux", package = "flux-derive" }
flux-mongodb = { git = "https://github.com/merelles/flux", package = "flux-mongodb" }
flux-postgres = { git = "https://github.com/merelles/flux", package = "flux-postgres" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
mongodb = "3"
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
uuid = { version = "1", features = ["v4", "serde"] }
