use std::{env, sync::Arc};

use anyhow::{Context, Result};
use flux::{
    AggregateRepository, AggregateRoot, GraphSaveMode, Include, ReadRepository, RelationMetadata,
};
use flux_derive::{AggregateRoot, Entity, SqlEntity};
use flux_postgres::{PostgresAggregate, PostgresRepository};
use tokio_postgres::NoTls;
use uuid::Uuid;

#[derive(Clone, Debug, Entity, SqlEntity)]
#[table_name = "cookbook_rollback_items"]
struct RollbackItem {
    #[primary_key]
    item_id: Uuid,
    order_id: Uuid,
    product_name: String,
    quantity: i32,
}

#[derive(Clone, Debug, Entity, SqlEntity, AggregateRoot)]
#[table_name = "cookbook_rollback_orders"]
struct RollbackOrder {
    #[primary_key]
    order_id: Uuid,
    customer_name: String,

    #[has_many(foreign_key = "order_id", references = "order_id")]
    items: Vec<RollbackItem>,
}

#[flux_postgres::async_trait]
impl PostgresAggregate for RollbackOrder {
    async fn load_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "items") {
            aggregate.items = repository
                .load_has_many::<RollbackItem, _>(relation("items"), &aggregate.order_id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<RollbackItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.order_id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<RollbackItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.order_id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &PostgresRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<RollbackItem, _>(relation("items"), id)
            .await
    }
}

fn relation(name: &str) -> &'static RelationMetadata {
    RollbackOrder::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let (client, connection) = connect_postgres().await?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("postgres connection error: {error}");
        }
    });

    client
        .batch_execute(
            r#"
            CREATE TABLE IF NOT EXISTS cookbook_rollback_orders (
                order_id UUID PRIMARY KEY,
                customer_name TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_rollback_items (
                item_id UUID PRIMARY KEY,
                order_id UUID NOT NULL REFERENCES cookbook_rollback_orders(order_id) ON DELETE CASCADE,
                product_name TEXT NOT NULL,
                quantity INTEGER NOT NULL CHECK (quantity > 0)
            );
            "#,
        )
        .await
        .context("failed to create rollback schema")?;

    let repo = PostgresRepository::<RollbackOrder>::new(Arc::new(client));
    let order_id = Uuid::new_v4();
    let invalid_order = RollbackOrder {
        order_id,
        customer_name: "Ada".to_string(),
        items: vec![RollbackItem {
            item_id: Uuid::new_v4(),
            order_id,
            product_name: "Keyboard".to_string(),
            quantity: 0,
        }],
    };

    let result = repo.insert_graph(&invalid_order).await;
    assert!(result.is_err());
    assert!(!repo
        .exists(&order_id)
        .await
        .context("check rollback root")?);

    Ok(())
}

async fn connect_postgres() -> Result<(
    tokio_postgres::Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    let url = env::var("POSTGRES_URL").unwrap_or_else(|_| {
        "postgres://postgres:postgres@localhost:5432/flux_cookbook".to_string()
    });
    tokio_postgres::connect(&url, NoTls)
        .await
        .context("failed to connect to PostgreSQL")
}
