use std::env;

use anyhow::{Context, Result};
use flux::{
    AggregateRepository, AggregateRoot, GraphSaveMode, Include, ReadRepository, RelationMetadata,
};
use flux_derive::{AggregateRoot, Entity, MongoEntity};
use flux_mongodb::{MongoAggregate, MongoObjectId, MongoRepository};
use mongodb::{
    bson::{doc, oid::ObjectId},
    Client,
};

#[derive(Clone, Debug, Entity, MongoEntity)]
#[collection_name = "cookbook_mongo_rollback_items"]
struct RollbackItem {
    #[primary_key]
    id: MongoObjectId,
    order_id: MongoObjectId,
    product_name: String,
}

#[derive(Clone, Debug, Entity, MongoEntity, AggregateRoot)]
#[collection_name = "cookbook_mongo_rollback_orders"]
struct RollbackOrder {
    #[primary_key]
    id: MongoObjectId,
    customer_name: String,

    #[has_many(foreign_key = "order_id", references = "id")]
    items: Vec<RollbackItem>,
}

#[flux_mongodb::async_trait]
impl MongoAggregate for RollbackOrder {
    async fn load_relations(
        repository: &MongoRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "items") {
            aggregate.items = repository
                .load_has_many::<RollbackItem, _>(relation("items"), &aggregate.id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<RollbackItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<RollbackItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &MongoRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<RollbackItem, _>(relation("items"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let database = connect_mongo().await?;
    clear_collections(
        &database,
        &[
            "cookbook_mongo_rollback_orders",
            "cookbook_mongo_rollback_items",
        ],
    )
    .await?;

    let repo = MongoRepository::<RollbackOrder>::new(database);
    let order_id = MongoObjectId(ObjectId::new());
    let duplicate_item_id = MongoObjectId(ObjectId::new());
    let invalid_order = RollbackOrder {
        id: order_id,
        customer_name: "Ada".to_string(),
        items: vec![
            RollbackItem {
                id: duplicate_item_id,
                order_id,
                product_name: "Keyboard".to_string(),
            },
            RollbackItem {
                id: duplicate_item_id,
                order_id,
                product_name: "Mouse".to_string(),
            },
        ],
    };

    let result = repo.insert_graph(&invalid_order).await;
    assert!(result.is_err());
    assert!(!repo
        .exists(&order_id)
        .await
        .context("check Mongo rollback root")?);

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    RollbackOrder::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn clear_collections(database: &mongodb::Database, names: &[&str]) -> Result<()> {
    for name in names {
        database
            .collection::<mongodb::bson::Document>(name)
            .delete_many(doc! {})
            .await
            .with_context(|| format!("clear Mongo collection {name}"))?;
    }
    Ok(())
}

async fn connect_mongo() -> Result<mongodb::Database> {
    let uri = env::var("MONGO_URI").unwrap_or_else(|_| "mongodb://localhost:27017".to_string());
    let database_name = env::var("MONGO_DATABASE").unwrap_or_else(|_| "flux_cookbook".to_string());
    let client = Client::with_uri_str(&uri)
        .await
        .context("failed to connect to MongoDB")?;
    client
        .database("admin")
        .run_command(doc! { "ping": 1 })
        .await
        .context("failed to ping MongoDB")?;
    Ok(client.database(&database_name))
}
