[package]
name = "flux-mongodb-graph-save"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
description = "Flux MongoDB graph save example"
repository.workspace = true

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
flux.workspace = true
flux-derive.workspace = true
flux-mongodb.workspace = true
mongodb.workspace = true
tokio.workspace = true
