use std::{env, sync::Arc};

use anyhow::{Context, Result};
use flux::{AggregateRepository, AggregateRoot, GraphSaveMode, Include, RelationMetadata};
use flux_derive::{AggregateRoot, Entity, SqlEntity};
use flux_postgres::{PostgresAggregate, PostgresRepository};
use tokio_postgres::NoTls;
use uuid::Uuid;

#[derive(Clone, Debug, Entity, SqlEntity)]
#[table_name = "cookbook_user_profiles"]
struct UserProfile {
    #[primary_key]
    profile_id: Uuid,
    user_id: Uuid,
    bio: String,
}

#[derive(Clone, Debug, Entity, SqlEntity, AggregateRoot)]
#[table_name = "cookbook_users_has_one"]
struct User {
    #[primary_key]
    user_id: Uuid,
    name: String,

    #[has_one(
        foreign_key = "user_id",
        references = "user_id",
        on_replace = "delete_missing"
    )]
    profile: Option<UserProfile>,
}

#[flux_postgres::async_trait]
impl PostgresAggregate for User {
    async fn load_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "profile") {
            aggregate.profile = repository
                .load_has_one::<UserProfile, _>(relation("profile"), &aggregate.user_id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_one::<UserProfile, _>(
                relation("profile"),
                aggregate.profile.as_ref(),
                &aggregate.user_id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_one::<UserProfile, _>(
                relation("profile"),
                aggregate.profile.as_ref(),
                &aggregate.user_id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &PostgresRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<UserProfile, _>(relation("profile"), id)
            .await
    }
}

fn relation(name: &str) -> &'static RelationMetadata {
    User::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let (client, connection) = connect_postgres().await?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("postgres connection error: {error}");
        }
    });

    client
        .batch_execute(
            r#"
            CREATE TABLE IF NOT EXISTS cookbook_users_has_one (
                user_id UUID PRIMARY KEY,
                name TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_user_profiles (
                profile_id UUID PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES cookbook_users_has_one(user_id) ON DELETE CASCADE,
                bio TEXT NOT NULL
            );
            "#,
        )
        .await
        .context("failed to create has-one schema")?;

    let repo = PostgresRepository::<User>::new(Arc::new(client));
    let user_id = Uuid::new_v4();
    let user = User {
        user_id,
        name: "Ada".to_string(),
        profile: Some(UserProfile {
            profile_id: Uuid::new_v4(),
            user_id,
            bio: "First programmer".to_string(),
        }),
    };

    let saved = repo
        .save_graph(&user, GraphSaveMode::UpsertChildren)
        .await
        .context("save has-one graph")?;
    let loaded = repo
        .find_graph_by_id(&saved.user_id, &[User::profile()])
        .await
        .context("load has-one graph")?;

    assert!(loaded.profile.is_some());

    Ok(())
}

async fn connect_postgres() -> Result<(
    tokio_postgres::Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    let url = env::var("POSTGRES_URL").unwrap_or_else(|_| {
        "postgres://postgres:postgres@localhost:5432/flux_cookbook".to_string()
    });
    tokio_postgres::connect(&url, NoTls)
        .await
        .context("failed to connect to PostgreSQL")
}
