use std::{env, sync::Arc};

use anyhow::{Context, Result};
use flux::{AggregateRepository, AggregateRoot, GraphSaveMode, Include, RelationMetadata};
use flux_derive::{AggregateRoot, Entity, SqlEntity};
use flux_postgres::{PostgresAggregate, PostgresRepository};
use tokio_postgres::NoTls;
use uuid::Uuid;

#[derive(Clone, Debug, Entity, SqlEntity)]
#[table_name = "cookbook_graph_save_items"]
struct OrderItem {
    #[primary_key]
    item_id: Uuid,
    order_id: Uuid,
    product_name: String,
    quantity: i32,
}

#[derive(Clone, Debug, Entity, SqlEntity, AggregateRoot)]
#[table_name = "cookbook_graph_save_orders"]
struct Order {
    #[primary_key]
    order_id: Uuid,
    customer_name: String,

    #[has_many(
        foreign_key = "order_id",
        references = "order_id",
        on_replace = "delete_missing"
    )]
    items: Vec<OrderItem>,
}

#[flux_postgres::async_trait]
impl PostgresAggregate for Order {
    async fn load_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "items") {
            aggregate.items = repository
                .load_has_many::<OrderItem, _>(relation("items"), &aggregate.order_id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<OrderItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.order_id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<OrderItem, _>(
                relation("items"),
                aggregate.items.as_slice(),
                &aggregate.order_id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &PostgresRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<OrderItem, _>(relation("items"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let (client, connection) = connect_postgres().await?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("postgres connection error: {error}");
        }
    });

    client
        .batch_execute(
            r#"
            CREATE TABLE IF NOT EXISTS cookbook_graph_save_orders (
                order_id UUID PRIMARY KEY,
                customer_name TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_graph_save_items (
                item_id UUID PRIMARY KEY,
                order_id UUID NOT NULL REFERENCES cookbook_graph_save_orders(order_id) ON DELETE CASCADE,
                product_name TEXT NOT NULL,
                quantity INTEGER NOT NULL
            );
            "#,
        )
        .await
        .context("failed to create graph save schema")?;

    let repo = PostgresRepository::<Order>::new(Arc::new(client));
    let order_id = Uuid::new_v4();
    let keyboard_id = Uuid::new_v4();
    let order = Order {
        order_id,
        customer_name: "Ada".to_string(),
        items: vec![
            OrderItem {
                item_id: keyboard_id,
                order_id,
                product_name: "Keyboard".to_string(),
                quantity: 1,
            },
            OrderItem {
                item_id: Uuid::new_v4(),
                order_id,
                product_name: "Mouse".to_string(),
                quantity: 2,
            },
        ],
    };

    repo.insert_graph(&order)
        .await
        .context("insert order graph")?;

    let replacement = Order {
        items: vec![OrderItem {
            item_id: keyboard_id,
            order_id,
            product_name: "Keyboard".to_string(),
            quantity: 3,
        }],
        ..order
    };

    let saved = repo
        .save_graph(&replacement, GraphSaveMode::ReplaceChildren)
        .await
        .context("replace order graph children")?;
    let loaded = repo
        .find_graph_by_id(&saved.order_id, &[Order::items()])
        .await
        .context("load order graph")?;

    assert_eq!(loaded.items.len(), 1);
    assert_eq!(loaded.items[0].quantity, 3);

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    Order::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn connect_postgres() -> Result<(
    tokio_postgres::Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    let url = env::var("POSTGRES_URL").unwrap_or_else(|_| {
        "postgres://postgres:postgres@localhost:5432/flux_cookbook".to_string()
    });
    tokio_postgres::connect(&url, NoTls)
        .await
        .context("failed to connect to PostgreSQL")
}
