use std::{env, sync::Arc};

use anyhow::{Context, Result};
use flux::{
    AggregateRepository, AggregateRoot, GraphSaveMode, Include, PageRequest, ReadRepository,
    RelationMetadata, RelationRepository,
};
use flux_derive::{AggregateRoot, Entity, SqlEntity};
use flux_postgres::{PostgresAggregate, PostgresRepository};
use tokio_postgres::NoTls;
use uuid::Uuid;

#[derive(Clone, Debug, Entity, SqlEntity)]
#[table_name = "cookbook_graph_delete_tasks"]
struct ProjectTask {
    #[primary_key]
    task_id: Uuid,
    project_id: Uuid,
    title: String,
}

#[derive(Clone, Debug, Entity, SqlEntity, AggregateRoot)]
#[table_name = "cookbook_graph_delete_projects"]
struct Project {
    #[primary_key]
    project_id: Uuid,
    name: String,

    #[has_many(foreign_key = "project_id", references = "project_id", cascade_delete)]
    tasks: Vec<ProjectTask>,
}

#[flux_postgres::async_trait]
impl PostgresAggregate for Project {
    async fn load_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "tasks") {
            aggregate.tasks = repository
                .load_has_many::<ProjectTask, _>(relation("tasks"), &aggregate.project_id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<ProjectTask, _>(
                relation("tasks"),
                aggregate.tasks.as_slice(),
                &aggregate.project_id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<ProjectTask, _>(
                relation("tasks"),
                aggregate.tasks.as_slice(),
                &aggregate.project_id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &PostgresRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<ProjectTask, _>(relation("tasks"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let (client, connection) = connect_postgres().await?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("postgres connection error: {error}");
        }
    });

    client
        .batch_execute(
            r#"
            CREATE TABLE IF NOT EXISTS cookbook_graph_delete_projects (
                project_id UUID PRIMARY KEY,
                name TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_graph_delete_tasks (
                task_id UUID PRIMARY KEY,
                project_id UUID NOT NULL REFERENCES cookbook_graph_delete_projects(project_id) ON DELETE CASCADE,
                title TEXT NOT NULL
            );
            "#,
        )
        .await
        .context("failed to create graph delete schema")?;

    let client = Arc::new(client);
    let project_repo = PostgresRepository::<Project>::new(Arc::clone(&client));
    let task_repo = PostgresRepository::<ProjectTask>::new(Arc::clone(&client));
    let project_id = Uuid::new_v4();
    let project = Project {
        project_id,
        name: "Flux cookbook".to_string(),
        tasks: vec![
            ProjectTask {
                task_id: Uuid::new_v4(),
                project_id,
                title: "Write graph example".to_string(),
            },
            ProjectTask {
                task_id: Uuid::new_v4(),
                project_id,
                title: "Verify delete cascade".to_string(),
            },
        ],
    };

    project_repo
        .insert_graph(&project)
        .await
        .context("insert project graph")?;
    let deleted = project_repo
        .delete_graph(&project_id)
        .await
        .context("delete project graph")?;
    let remaining_tasks = task_repo
        .find_by_foreign_key("project_id", &project_id, PageRequest::cursor(10, None))
        .await
        .context("find tasks after graph delete")?;

    assert!(deleted);
    assert!(!project_repo
        .exists(&project_id)
        .await
        .context("check deleted project")?);
    assert!(remaining_tasks.items.is_empty());

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    Project::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn connect_postgres() -> Result<(
    tokio_postgres::Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    let url = env::var("POSTGRES_URL").unwrap_or_else(|_| {
        "postgres://postgres:postgres@localhost:5432/flux_cookbook".to_string()
    });
    tokio_postgres::connect(&url, NoTls)
        .await
        .context("failed to connect to PostgreSQL")
}
