[package]
name = "flux-postgres-bulk"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
description = "Flux PostgreSQL bulk write example"
repository.workspace = true

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
flux.workspace = true
flux-derive.workspace = true
flux-postgres.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
uuid.workspace = true
