use std::env;

use anyhow::{Context, Result};
use flux::{
    AggregateRepository, AggregateRoot, GraphSaveMode, Include, PageRequest, ReadRepository,
    RelationMetadata, RelationRepository,
};
use flux_derive::{AggregateRoot, Entity, MongoEntity};
use flux_mongodb::{MongoAggregate, MongoObjectId, MongoRepository};
use mongodb::{
    bson::{doc, oid::ObjectId},
    Client,
};

#[derive(Clone, Debug, Entity, MongoEntity)]
#[collection_name = "cookbook_mongo_graph_tasks"]
struct ProjectTask {
    #[primary_key]
    id: MongoObjectId,
    project_id: MongoObjectId,
    title: String,
}

#[derive(Clone, Debug, Entity, MongoEntity, AggregateRoot)]
#[collection_name = "cookbook_mongo_graph_projects"]
struct Project {
    #[primary_key]
    id: MongoObjectId,
    name: String,

    #[has_many(foreign_key = "project_id", references = "id", cascade_delete)]
    tasks: Vec<ProjectTask>,
}

#[flux_mongodb::async_trait]
impl MongoAggregate for Project {
    async fn load_relations(
        repository: &MongoRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "tasks") {
            aggregate.tasks = repository
                .load_has_many::<ProjectTask, _>(relation("tasks"), &aggregate.id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<ProjectTask, _>(
                relation("tasks"),
                aggregate.tasks.as_slice(),
                &aggregate.id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &MongoRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_has_many::<ProjectTask, _>(
                relation("tasks"),
                aggregate.tasks.as_slice(),
                &aggregate.id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &MongoRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_relation::<ProjectTask, _>(relation("tasks"), id)
            .await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let database = connect_mongo().await?;
    clear_collections(
        &database,
        &[
            "cookbook_mongo_graph_projects",
            "cookbook_mongo_graph_tasks",
        ],
    )
    .await?;

    let project_repo = MongoRepository::<Project>::new(database.clone());
    let task_repo = MongoRepository::<ProjectTask>::new(database);
    let project_id = MongoObjectId(ObjectId::new());
    let project = Project {
        id: project_id,
        name: "Flux cookbook".to_string(),
        tasks: vec![
            ProjectTask {
                id: MongoObjectId(ObjectId::new()),
                project_id,
                title: "Write Mongo graph example".to_string(),
            },
            ProjectTask {
                id: MongoObjectId(ObjectId::new()),
                project_id,
                title: "Verify Mongo cascade delete".to_string(),
            },
        ],
    };

    project_repo
        .insert_graph(&project)
        .await
        .context("insert Mongo project graph")?;
    let deleted = project_repo
        .delete_graph(&project_id)
        .await
        .context("delete Mongo project graph")?;
    let remaining_tasks = task_repo
        .find_by_foreign_key("project_id", &project_id, PageRequest::cursor(10, None))
        .await
        .context("find Mongo tasks after graph delete")?;

    assert!(deleted);
    assert!(!project_repo
        .exists(&project_id)
        .await
        .context("check deleted Mongo project")?);
    assert!(remaining_tasks.items.is_empty());

    Ok(())
}

fn relation(name: &str) -> &'static RelationMetadata {
    Project::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

async fn clear_collections(database: &mongodb::Database, names: &[&str]) -> Result<()> {
    for name in names {
        database
            .collection::<mongodb::bson::Document>(name)
            .delete_many(doc! {})
            .await
            .with_context(|| format!("clear Mongo collection {name}"))?;
    }
    Ok(())
}

async fn connect_mongo() -> Result<mongodb::Database> {
    let uri = env::var("MONGO_URI").unwrap_or_else(|_| "mongodb://localhost:27017".to_string());
    let database_name = env::var("MONGO_DATABASE").unwrap_or_else(|_| "flux_cookbook".to_string());
    let client = Client::with_uri_str(&uri)
        .await
        .context("failed to connect to MongoDB")?;
    client
        .database("admin")
        .run_command(doc! { "ping": 1 })
        .await
        .context("failed to ping MongoDB")?;
    Ok(client.database(&database_name))
}
