use std::{env, sync::Arc};

use anyhow::{Context, Result};
use flux::{AggregateRepository, AggregateRoot, GraphSaveMode, Include, RelationMetadata};
use flux_derive::{AggregateRoot, Entity, SqlEntity};
use flux_postgres::{PostgresAggregate, PostgresRepository};
use tokio_postgres::NoTls;
use uuid::Uuid;

#[derive(Clone, Debug, Entity, SqlEntity)]
#[table_name = "cookbook_courses"]
struct Course {
    #[primary_key]
    course_id: Uuid,
    title: String,
}

#[derive(Clone, Debug, Entity, SqlEntity, AggregateRoot)]
#[table_name = "cookbook_students"]
struct Student {
    #[primary_key]
    student_id: Uuid,
    name: String,

    #[many_to_many(
        join_table = "cookbook_enrollments",
        source_key = "student_id",
        target_key = "course_id",
        target_primary_key = "course_id",
        on_replace = "delete_missing"
    )]
    courses: Vec<Course>,
}

#[flux_postgres::async_trait]
impl PostgresAggregate for Student {
    async fn load_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &mut Self,
        includes: &[Include<Self>],
    ) -> flux::Result<()> {
        if includes.iter().any(|include| include.name == "courses") {
            aggregate.courses = repository
                .load_many_to_many::<Course, _>(relation("courses"), &aggregate.student_id)
                .await?;
        }
        Ok(())
    }

    async fn insert_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
    ) -> flux::Result<()> {
        repository
            .save_many_to_many::<Course, _>(
                relation("courses"),
                aggregate.courses.as_slice(),
                &aggregate.student_id,
                GraphSaveMode::AppendChildren,
            )
            .await
    }

    async fn update_relations(
        repository: &PostgresRepository<Self>,
        aggregate: &Self,
        mode: GraphSaveMode,
    ) -> flux::Result<()> {
        repository
            .save_many_to_many::<Course, _>(
                relation("courses"),
                aggregate.courses.as_slice(),
                &aggregate.student_id,
                mode,
            )
            .await
    }

    async fn delete_relations(
        repository: &PostgresRepository<Self>,
        id: &Self::Id,
    ) -> flux::Result<()> {
        repository
            .delete_many_to_many_links(relation("courses"), id)
            .await
    }
}

fn relation(name: &str) -> &'static RelationMetadata {
    Student::relations()
        .iter()
        .find(|relation| relation.name == name)
        .expect("relation generated by AggregateRoot")
}

#[tokio::main]
async fn main() -> Result<()> {
    dotenvy::dotenv().ok();

    let (client, connection) = connect_postgres().await?;
    tokio::spawn(async move {
        if let Err(error) = connection.await {
            eprintln!("postgres connection error: {error}");
        }
    });

    client
        .batch_execute(
            r#"
            CREATE TABLE IF NOT EXISTS cookbook_students (
                student_id UUID PRIMARY KEY,
                name TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_courses (
                course_id UUID PRIMARY KEY,
                title TEXT NOT NULL
            );

            CREATE TABLE IF NOT EXISTS cookbook_enrollments (
                student_id UUID NOT NULL REFERENCES cookbook_students(student_id) ON DELETE CASCADE,
                course_id UUID NOT NULL REFERENCES cookbook_courses(course_id) ON DELETE CASCADE,
                PRIMARY KEY (student_id, course_id)
            );
            "#,
        )
        .await
        .context("failed to create many-to-many schema")?;

    let repo = PostgresRepository::<Student>::new(Arc::new(client));
    let rust_course = Course {
        course_id: Uuid::new_v4(),
        title: "Rust".to_string(),
    };
    let databases_course = Course {
        course_id: Uuid::new_v4(),
        title: "Databases".to_string(),
    };
    let student = Student {
        student_id: Uuid::new_v4(),
        name: "Ada".to_string(),
        courses: vec![rust_course.clone(), databases_course],
    };

    repo.save_graph(&student, GraphSaveMode::ReplaceChildren)
        .await
        .context("save many-to-many graph")?;

    let replacement = Student {
        courses: vec![rust_course],
        ..student
    };
    let saved = repo
        .save_graph(&replacement, GraphSaveMode::ReplaceChildren)
        .await
        .context("replace many-to-many links")?;

    assert_eq!(saved.courses.len(), 1);

    Ok(())
}

async fn connect_postgres() -> Result<(
    tokio_postgres::Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    let url = env::var("POSTGRES_URL").unwrap_or_else(|_| {
        "postgres://postgres:postgres@localhost:5432/flux_cookbook".to_string()
    });
    tokio_postgres::connect(&url, NoTls)
        .await
        .context("failed to connect to PostgreSQL")
}
